# Generated by Django 3.0.3 on 2020-03-24 02:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_subject', models.CharField(max_length=40)),
                ('q_cat', models.CharField(max_length=40)),
                ('q_rank', models.CharField(max_length=20)),
                ('q_text', models.TextField(default='', null=True)),
                ('q_option1', models.CharField(default='', max_length=200)),
                ('q_option2', models.CharField(default='', max_length=200)),
                ('q_option3', models.CharField(default='', max_length=200)),
                ('q_option4', models.CharField(default='', max_length=200)),
                ('q_answer', models.CharField(max_length=20)),
                ('q_ask_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('no_times_ques_served', models.IntegerField(default=0)),
                ('no_times_anwered_correctly', models.IntegerField(default=0)),
                ('no_times_anwered_incorrectly', models.IntegerField(default=0)),
                ('difficulty_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(default='', max_length=100)),
                ('quiz_OrgIdentifier', models.CharField(default='', max_length=40)),
                ('quiz_questions', models.TextField(null=True)),
                ('quiz_noofquest', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_user', models.CharField(max_length=100)),
                ('c_tot_score', models.IntegerField(default=0)),
                ('c_cat_scores', models.TextField(default=0, null=True)),
                ('c_comment', models.TextField(default='', null=True)),
                ('c_new_quest', models.TextField(default='', null=True)),
                ('c_attempt_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_option', models.CharField(max_length=20)),
                ('is_correct', models.BooleanField(default=False)),
                ('ans_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIP.Question')),
            ],
        ),
    ]
