# Generated by Django 3.0.3 on 2020-03-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0002_result_c_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='c_total_ans_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='c_total_ans_incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='c_total_q_asked',
            field=models.IntegerField(default=0),
        ),
    ]
