# Generated by Django 3.0.3 on 2020-04-03 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0004_result_c_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(default='', max_length=200)),
                ('trainee_emails', models.TextField(null=True)),
                ('register_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
