# Generated by Django 3.0.3 on 2020-04-03 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0005_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_email', models.CharField(default='', max_length=100)),
                ('login_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
