# Generated by Django 3.0.3 on 2020-04-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0006_trainee_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='register_time',
            new_name='expire_time',
        ),
    ]
